apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  ports:
  - name: my-app
    port: 3000
    targetPort: 3000
  selector:
    app: my-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: aws-registry-url.dkr.ecr.us-west-1.amazonaws.com/my-app:latest
          ports:
            - name: web
              containerPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app
            port:
              number: 3000
