name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: Terraform/
        run: |
          terraform init

      - name: Terraform Plan
        working-directory: Terraform/
        run: terraform plan

      - name: Terraform Apply
        working-directory: Terraform/
        run: |
          terraform apply -auto-approve
          terraform output kubeconfig > ~/.kube/eks-cluster

      - name: Build and Push Docker Image
        working-directory: Application/
        run: |
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com
          docker build -t my-app .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com/my-app:latest
          export KUBECONFIG=~/.kube/eks-cluster

      - uses: actions/checkout@v2
      - name: Run kubectl
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "apply Application/deployment.yml"
        env:
          EKS_CLUSTER: my-cluster

      - uses: actions/checkout@v2
      - name: Run kubectl
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "get po -A"
        env:
          EKS_CLUSTER: my-cluster



